# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: fmt
        name: ruff format
        entry: uvx ruff format
        language: system
        files: '\.py$'

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.1.3"
    hooks:
      - id: pyproject-fmt
        args: ["pyproject.toml"]
        exclude: ^(examples/)
