app = "app"
version = "hatch version" # or "1.2.3"
build_command = "hatch build"
release_command = "#app setup"
requirements = "requirements.txt"
distfile = "dist/{app}-{version}-py3-none-any.whl" 
envfile = ".env.prod" # can be overriden on each hosts
tasks = { postgres = "deploy.postgres_tasks" }

[aliases]
console = ".venv/bin/app shell_plus"
migrate = ".venv/bin/app migrate"
shell_plus = "!app shell_plus"

[processes.web]
port = 8000
command = ".venv/bin/app prodserver"

[processes.worker]
command = "!app qcluster"

[hosts.main]
ip = "127.0.0.1"
domain = "myapp.com"
user = "tobi"
project_dir = ".local/share/fujin/app" # relative to user home
