app = "fujin-cli"
build_command = "uv build"
distfile = "dist/fujin-{version}-py3-none-any.whl"

[webserver]
upstream = "localhost:8000"
type = "fujin.proxies.caddy"

[hooks]
pre_deploy = ".venv/bin/fujin-cli setup"

[processes]
web = ".venv/bin/fujin-cli prodserver"
worker = ".venv/bin/fujin-cli qcluster"

[aliases]
console = "app exec -i shell_plus"
dbconsole = "app exec -i dbshell"
print_settings = "app exec print_settings --format=pprint"
shell = "server exec -i bash"

[hosts.primary]
ip = "127.0.0.1"
user = "root"
domain_name = "fujin.com"
envfile = ".env.prod"
default = true
