app = "bookstore"
#version = "0.1.0" infer from the pyproject.toml file
requirements = "requirements.txt"
python_version = "3.13"
build_command = "uv build"
release_command = "bookstore migrate"
distfile = "./../../../dist/bookstore-{version}-py3-none-any.whl"
webserver = { upstream = "localhost:8000" } # or "unix:/run/bookstore.sock"

[hooks.post_deploy]
pip_list = "uv pip list"
migrate = "bookstore migrate" # useless just so show the example

[aliases]
console = "app exec -i shell"
dbshell = "app exec -i dbshell"
shell = "server exec -i bash"

[processes]
web = ".venv/bin/bookstore runserver"
#worker = ".venv/bin/bookstore qcluster"

[hosts.primary]
default = true
ip = "127.0.0.1"
domain_name = "mybookstore.com"
envfile = ".env.prod"
user = "tobi"
key_filename = "/home/tobi/Builds/falcopackages/fujin/.vagrant/machines/default/virtualbox/private_key"
ssh_port = 2222
