#app = "bookstore"
#version = "0.1.0"
requirements = "requirements.txt"
build_command = "uv build"
release_command = "!bookstore migrate"
distfile = "dist/bookstore-{version}-py3-none-any.whl"
envfile = ".env.prod"

[aliases]
console = "app exec -i shell_plus"
dbshell = "app exec -i dbshell"

[processes.web]
port = 8000
# bind = "unix:/run/bookstore.sock" # bind and port are mutually exclusive
command = "!bookstore prodserver"

[processes.worker]
command = "!bookstore qcluster"

[hosts.primary]
ip = "127.0.0.1"
domain_name = "mybookstore.com"
user = "test"
password_env = "TEST_PASSWORD"
key_filename = "./../../../id_rsa"
ssh_port = 2222
# project_dir = ".local/share/fujin/bookstore" # relative to user home
